### ISSUE TITLE
Error when trying to parse IDL with module [4796]

### ISSUE THREAD

**Issue by glchua2** [eProsima/IDL-Parser#12]
When trying to parse HelloWorld.idl with the following command `microxrceddsgen HelloWorld.idl`, I received the following error:

`Loading templates...`
`Processing the file HelloWorld.idl...`
`Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64`
`Copyright (C) Microsoft Corporation.  All rights reserved.`
`HelloWorld.idl`
`ERROR<Exception>: Can't find template module.st; group hierarchy is [Common]`

Content of HelloWorld.idl:
`module HelloWorldModule {
	struct HelloWorld
	{
		unsigned long index;
		string message;
	};
};`

**Comment by glchua2** [comment]
Any insights into this?

**Comment by BorjaOuterelo** [comment]
Hi @glchua2 

Sorry for the delay.

Currently, `microxrceddsgen` does not support modules.
However `fastrtpsgen` does: [fastrtpsgen](https://github.com/eProsima/Fast-RTPS/tree/master/fastrtpsgen)

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if you have more questions.
