### ISSUE TITLE
Idl typedef scenarios

### ISSUE THREAD

**Issue by drorbashan** [eProsima/IDL-Parser#13]
Hi,

I am trying to parse the following two typedef scenarios:

  1. Multiple typedef levels
      typedef short T_Short;
      typedef T_short TT_Short;

  I am getting that TT_Short is short, which is correct, but can I get the information that TT_Short goes through T_short and then to short?

  2.  typedef sequence <char, 500> T_LongString;

     Trying to parse it with the following code
     for (TypeDeclaration typdef : context.getTypes()) {
         System.out.println("TypeDef Name " + typdef.getName() + " " + 
                        kind.getTypeName(typdef.getTypeCode().getKind()));
	 if (typdef.getTypeCode() instanceof AliasTypeCode) {
	    AliasTypeCode aliasCode = (AliasTypeCode)typdef.getTypeCode();
	    System.out.println("Next Level is " + aliasCode.getContentTypeCode().getClass().getName());
 	 }
     }

     I am getting
     TypeDef Name T_LongString alias, indicating that T_LongString is AliasTypeCode
     Next Level is com.eprosima.idl.parser.typecode.PrimitiveTypeCode, indicating the char primitive
  
     Where I can find all the "sequence <char, 500>" information?

Tx,
Dror.

**Comment by LuisGP** [comment]
Hi Dror,

I think in both cases you are looking for `AliasTypeCode.getTypedefContentTypeCode()` method instead of `getContentTypeCode`. 
`getTypedefContentTypeCode` doesn't unrolls the aliases or container type codes until the base type.

Best regards.

**Comment by drorbashan** [comment]
Yes, exactly what I needed.
Great,
Tx & Regards,
