### ISSUE TITLE
FastRTPSGen: parsing multi-line comments results in error [6299]

### ISSUE THREAD

**Issue by TSC21** [eProsima/IDL-Parser#33]
`FastRTPSGen` doesn't handle very well line breaks/new lines in comments - or multi-line comments. For example:
```
# Optical flow in XYZ body frame in SI units.
# Check http://en.wikipedia.org/wiki/International_System_of_Units
```

Which results in:
```c++
    @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.
 Check http://en.wikipedia.org/wiki/International_System_of_Units")
```

Which turns into an error in the parser:
```sh
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:8:41: warning: missing terminating " character
     @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.
                                         ^
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:11:27: error: mismatched input 'comment' expecting {',', ')', '/', '*', '+', '-', '^', '&', '|', '%', '>>', '<<'}
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:11:82: error: no viable alternative at input '")\n      uint64 timestamp;\n\n      @verbatim (language="'
```

Is this something we should predict on the message file so to be defined correctly on the IDL or is this a bug on the `FastRTPSGen` parser and it needs to be fixed?

**Comment by LuisGP** [comment]
[LuisGP](https://github.com/eProsima/Fast-RTPS/issues/690#issuecomment-528289476)
[TSC21](https://github.com/eProsima/Fast-RTPS/issues/690#issuecomment-528290048)
[TSC21](https://github.com/eProsima/Fast-RTPS/issues/690#issuecomment-528294061)

**Comment by TSC21** [comment]
@LuisGP we can add a `\` character to the comment, but does it still respect section 7.2.6.3 of the IDL 4.2 specification? Should the IDL parser consider the new line as a new comment instead?

**Comment by TSC21** [comment]
Also, I do get a warning if I try to add a backlash + whitespace + newline:
```sh
warning: backslash and newline separated by space
```
Looking at https://github.com/ros2/rosidl/blob/master/rosidl_adapter/rosidl_adapter/resource/struct.idl.em#L49, I don't see an obvious way of adding the backlash together with the newline without adding a whitespace so they don't null themselves.

**Comment by TSC21** [comment]
This was solved with https://github.com/ros2/rosidl/pull/410. @LuisGP thanks for your inputs.

**Comment by TSC21** [comment]
Actually, I just saw https://github.com/eProsima/IDL-Parser/pull/35. I suppose it works in parallel with the PR on `rosidl`.

**Comment by LuisGP** [comment]
You're right. Once that PR is merged, Fast-RTPS-Gen could upgrade its IDL-Parser dependency and make use of the new feature.

**Comment by TSC21** [comment]
Great! Are you planning to do those merges today?

**Comment by LuisGP** [comment]
I don't know. Both #35 and #36 need to be reviewed by another teammate. I'll try to accelerate the process as both PR are small enough (but require a lot of time to test them properly) to do the merges ASAP.

**Comment by TSC21** [comment]
> I don't know. Both #35 and #36 need to be reviewed by another teammate. I'll try to accelerate the process as both PR are small enough (but require a lot of time to test them properly) to do the merges ASAP.

Perfect! Thank you!
