### ISSUE TITLE
Illegal identifier: ... is already defined (Annotation: ...) [6318]

### ISSUE THREAD

**Issue by TSC21** [eProsima/IDL-Parser#34]
Using Fast-RTPS latest upstream master. FastRTPSGen 1.9.0.

Trying to parse the following IDL file:
```
#ifndef __trajectory_waypoint__idl__
#define __trajectory_waypoint__idl__

typedef float trajectory_waypoint__float_array_3[3];

struct trajectory_waypoint
{
    unsigned long long timestamp;
    trajectory_waypoint__float_array_3 position;
    trajectory_waypoint__float_array_3 velocity;
    trajectory_waypoint__float_array_3 acceleration;
    float yaw;
    float yaw_speed;
    boolean point_valid;
    octet type;

}; // struct trajectory_waypoint

#pragma keylist trajectory_waypoint

#endif  // __trajectory_waypoint__idl__
```

Results in the following error:
```sh
/home/nuno/PX4/Firmware/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_client/micrortps_agent/idl/trajectory_waypoint.idl:12:47: error: Illegal identifier: position is already defined (Annotation: position)
```

@LuisGP can you provide a pointer on why is it happening? Also this same IDL is include on another IDL that depends on this (nested type).

Note that this IDL was being parsed alright on version 1.9.0.

Thanks in advance for your help!

**Comment by TSC21** [comment]
Note that another version of the same message (PascalCase'd), but with a IDL compatible with 4.2:
```
// generated from rosidl_adapter/resource/msg.idl.em
// with input from px4_msgs/msg/TrajectoryWaypoint.msg
// generated code does not contain a copyright notice


module px4_msgs {
  module msg {
    typedef float float__3[3];
    @verbatim (language="comment", text=" Waypoint Trajectory description. See also Mavlink TRAJECTORY msg")
    @verbatim (language="comment", text=" The topic trajectory_waypoint describe each waypoint defined in vehicle_trajectory_waypoint")
    struct TrajectoryWaypoint {
      @verbatim (language="comment", text=" time since system start (microseconds)")
      uint64 timestamp;

      float__3 position;

      float__3 velocity;

      float__3 acceleration;

      float yaw;

      float yaw_speed;

      boolean point_valid;

      uint8 type;
    };
  };
};
```
Is correctly parsed without the reported issue.

**Comment by LuisGP** [comment]
Hi @TSC21 

The problem is that `position` is a builtin annotation from IDL 4.2. We added this annotations recently.
You can avoid name collision checkings adding a the prefix "_":

    trajectory_waypoint__float_array_3 _position;

The resulting code will be with the member named `position` without the prefix.
Probably name collision shouldn't be checked against annotations, but we will discuss it internally.

Best regards.

**Comment by TSC21** [comment]
> Hi @TSC21
> 
> The problem is that `position` is a builtin annotation from IDL 4.2. We added this annotations recently.
> You can avoid name collision checkings adding a the prefix "_":
> 
> ```
> trajectory_waypoint__float_array_3 _position;
> ```
> 
> The resulting code will be with the member named `position` without the prefix.
> Probably name collision shouldn't be checked against annotations, but we will discuss it internally.
> 
> Best regards.

@LuisGP I would understand that if it wasn't working as well in the IDL file I presented in https://github.com/eProsima/IDL-Parser/issues/34#issuecomment-528886219. As you can see, there is:

```
      float__3 position;
```
So, the exact same naming. And it parses correctly.

**Comment by LuisGP** [comment]
> So, the exact same naming. And it parses correctly. So there needs to be some inconsistency here, since I use the same parser exactly the same way on both IDL files.

Yes, it is very likely to parse successfully because of the modules. We will review how naming collision works against annotations.

**Comment by TSC21** [comment]
> > So, the exact same naming. And it parses correctly. So there needs to be some inconsistency here, since I use the same parser exactly the same way on both IDL files.
> 
> Yes, it is very likely to parse successfully because of the modules. We will review how naming collision works against annotations.

So what can I do in this case? Should I wait your feedback? Changing the naming on fields will be problematic in some way.

**Comment by LuisGP** [comment]
The quickest solution is to add the underscore prefix because the generated code will work with any existing code (remember that that prefix will be ignored and removed from the final member name). In this case, only the original *msg* file should be modified.

I don't know when we could review the name collision, but we created the task already.

**Comment by TSC21** [comment]
> The quickest solution is to add the underscore prefix because the generated code will work with any existing code (remember that that prefix will be ignored and removed from the final member name). In this case, only the original msg file should be modified.

That's not a solution at all for our case. [PX4 msg definitions]() have a lot of fields with naming that may collide with the annotations. It doesn't make any sense to change a full message spec, with multiple field renaming, just because of a feature that verifies annotations and looks for naming collision. I think it would rather make sense to add an option to FastRTPSGen that deactivates annotation collision check or rather review the naming collision as you said.

This is currently a blocker for us to upgrade to Fast-RTPS 1.9.
