### ISSUE TITLE
Struct case-insensitivity: parser error when field name matches existing Struct name, regardless of casing

### ISSUE THREAD

**Issue by pwolf15** [eProsima/IDL-Parser#38]
**Steps to reproduce**

1. Created IDL, test.idl, with contents below:
``` idl
struct A
{
    int32 int_value;
};

struct B
{
    A a;
};
```
2. fastrtpsgen -example CMake -replace test.idl

**Current behavior:**

``` bash
Loading templates...
Processing the file test.idl...
test.idl:8:7: error: Illegal identifier: a is already defined (Definition: com.eprosima.idl.parser.tree.TypeDeclaration@78e67e0a)
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:336)
        at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1199)
```

**Expected behavior:**

IDL parser should generate valid C++ definitions.

**Comment by LuisGP** [comment]
Hi @pwolf15 

As the [IDL 4.2](https://www.omg.org/spec/IDL/4.2/PDF) standard defined (section 7.2.3.1)

> Identifiers that differ only in case collide, and will yield a compilation error under certain circumstances. An identifier for a given definition must be spelled identically (e.g., with respect to case) throughout a specification.

So, the IDL-Parser is working as expected.

The standard way to work around this feature, is to prefix an underscore to the member identifier:

```idl
struct B
{
    A _a;
};
```

If you need to support these kind of IDLs and cannot be changed, `fastrtpsgen` allows you to apply case sensitive parsing with the `-cs` option:

> -cs: IDL grammar apply case sensitive matching.

    fastrtpsgen -example CMake -replace -cs test.idl

**Comment by pwolf15** [comment]
Great, thanks! Worked as expected. I was unaware of the rule. rtiddsgen, RTI's generator, succeeded without error on the same kind of input. Additionally, I also just now noticed the -cs option in the usage message.
