### ISSUE TITLE
is master working? Kiara problem [4409]

### ISSUE THREAD

**Issue by rafaeling** [eProsima/IDL-Parser#4]
Hi,

I got this error while trying to build with mvn package on a linux system!!
Any hints are welcome!!

Greetings :)

[INFO] Processing grammar: kiara/KIARAIDL.g4
[ERROR] error(79): kiara/KIARAIDL.g4:355:6: missing argument(s) on rule reference: export
[ERROR] /home/rafa/Escritorio/Fast-RTPS/thirdparty/idl/kiara/KIARAIDL.g4 [355:6]: missing argument(s) on rule reference: export

**Comment by richiware** [comment]
Sorry for the delay. I misplaced the issue. Currently we don't maintain the KIARA grammar. Our efforts are focused on the C++ implementation [Fast RTPS](https://github.com/eProsima/Fast-RTPS). I encourage you to test the C++ implementation.

**Comment by richiware** [comment]
This issue might be related with #8. Are you trying to generate the IDL grammar parser or de KIARA grammar parser?

**Comment by richiware** [comment]
Can you test with current master? Maybe #9 solves your issue.

**Comment by LuisGP** [comment]
I'm closing this issue because it was answered time ago and a potential solution was suggested.
@rafaeling feel free to reopen it if the problem persists.
